spring:
  application:
    name: elephant
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
logging:
  level:
    io.micrometer.core.instrument.logging: INFO
    root: INFO