spring:
  application:
    name: elephant
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  threads:
    virtual:
      enabled: true
logging:
  level:
    io.micrometer.core.instrument.logging: INFO
    root: INFO
grpc:
  port: 8081