// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hello.proto
// Protobuf Java Version: 4.29.3

package com.linfp.elephant.grpc;

/**
 * Protobuf type {@code hello.HelloParam}
 */
public final class HelloParam extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:hello.HelloParam)
        HelloParamOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                HelloParam.class.getName());
    }

    // Use HelloParam.newBuilder() to construct.
    private HelloParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private HelloParam() {
        arg1_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.linfp.elephant.grpc.HelloProto.internal_static_hello_HelloParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.linfp.elephant.grpc.HelloProto.internal_static_hello_HelloParam_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.linfp.elephant.grpc.HelloParam.class, com.linfp.elephant.grpc.HelloParam.Builder.class);
    }

    public static final int ARG1_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object arg1_ = "";

    /**
     * <code>string arg1 = 1;</code>
     *
     * @return The arg1.
     */
    @java.lang.Override
    public java.lang.String getArg1() {
        java.lang.Object ref = arg1_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            arg1_ = s;
            return s;
        }
    }

    /**
     * <code>string arg1 = 1;</code>
     *
     * @return The bytes for arg1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getArg1Bytes() {
        java.lang.Object ref = arg1_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            arg1_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ARG2_FIELD_NUMBER = 2;
    private int arg2_ = 0;

    /**
     * <code>int32 arg2 = 2;</code>
     *
     * @return The arg2.
     */
    @java.lang.Override
    public int getArg2() {
        return arg2_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(arg1_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, arg1_);
        }
        if (arg2_ != 0) {
            output.writeInt32(2, arg2_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(arg1_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, arg1_);
        }
        if (arg2_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, arg2_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.linfp.elephant.grpc.HelloParam)) {
            return super.equals(obj);
        }
        com.linfp.elephant.grpc.HelloParam other = (com.linfp.elephant.grpc.HelloParam) obj;

        if (!getArg1()
                .equals(other.getArg1())) return false;
        if (getArg2()
                != other.getArg2()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ARG1_FIELD_NUMBER;
        hash = (53 * hash) + getArg1().hashCode();
        hash = (37 * hash) + ARG2_FIELD_NUMBER;
        hash = (53 * hash) + getArg2();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.linfp.elephant.grpc.HelloParam parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.linfp.elephant.grpc.HelloParam parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.linfp.elephant.grpc.HelloParam parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.linfp.elephant.grpc.HelloParam prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code hello.HelloParam}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:hello.HelloParam)
            com.linfp.elephant.grpc.HelloParamOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.linfp.elephant.grpc.HelloProto.internal_static_hello_HelloParam_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.linfp.elephant.grpc.HelloProto.internal_static_hello_HelloParam_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.linfp.elephant.grpc.HelloParam.class, com.linfp.elephant.grpc.HelloParam.Builder.class);
        }

        // Construct using com.linfp.elephant.grpc.HelloParam.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            arg1_ = "";
            arg2_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.linfp.elephant.grpc.HelloProto.internal_static_hello_HelloParam_descriptor;
        }

        @java.lang.Override
        public com.linfp.elephant.grpc.HelloParam getDefaultInstanceForType() {
            return com.linfp.elephant.grpc.HelloParam.getDefaultInstance();
        }

        @java.lang.Override
        public com.linfp.elephant.grpc.HelloParam build() {
            com.linfp.elephant.grpc.HelloParam result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.linfp.elephant.grpc.HelloParam buildPartial() {
            com.linfp.elephant.grpc.HelloParam result = new com.linfp.elephant.grpc.HelloParam(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.linfp.elephant.grpc.HelloParam result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.arg1_ = arg1_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.arg2_ = arg2_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.linfp.elephant.grpc.HelloParam) {
                return mergeFrom((com.linfp.elephant.grpc.HelloParam) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.linfp.elephant.grpc.HelloParam other) {
            if (other == com.linfp.elephant.grpc.HelloParam.getDefaultInstance()) return this;
            if (!other.getArg1().isEmpty()) {
                arg1_ = other.arg1_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (other.getArg2() != 0) {
                setArg2(other.getArg2());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            arg1_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 16: {
                            arg2_ = input.readInt32();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object arg1_ = "";

        /**
         * <code>string arg1 = 1;</code>
         *
         * @return The arg1.
         */
        public java.lang.String getArg1() {
            java.lang.Object ref = arg1_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                arg1_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string arg1 = 1;</code>
         *
         * @return The bytes for arg1.
         */
        public com.google.protobuf.ByteString
        getArg1Bytes() {
            java.lang.Object ref = arg1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                arg1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string arg1 = 1;</code>
         *
         * @param value The arg1 to set.
         * @return This builder for chaining.
         */
        public Builder setArg1(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            arg1_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string arg1 = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearArg1() {
            arg1_ = getDefaultInstance().getArg1();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>string arg1 = 1;</code>
         *
         * @param value The bytes for arg1 to set.
         * @return This builder for chaining.
         */
        public Builder setArg1Bytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            arg1_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private int arg2_;

        /**
         * <code>int32 arg2 = 2;</code>
         *
         * @return The arg2.
         */
        @java.lang.Override
        public int getArg2() {
            return arg2_;
        }

        /**
         * <code>int32 arg2 = 2;</code>
         *
         * @param value The arg2 to set.
         * @return This builder for chaining.
         */
        public Builder setArg2(int value) {

            arg2_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>int32 arg2 = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearArg2() {
            bitField0_ = (bitField0_ & ~0x00000002);
            arg2_ = 0;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:hello.HelloParam)
    }

    // @@protoc_insertion_point(class_scope:hello.HelloParam)
    private static final com.linfp.elephant.grpc.HelloParam DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.linfp.elephant.grpc.HelloParam();
    }

    public static com.linfp.elephant.grpc.HelloParam getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloParam>
            PARSER = new com.google.protobuf.AbstractParser<HelloParam>() {
        @java.lang.Override
        public HelloParam parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<HelloParam> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloParam> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.linfp.elephant.grpc.HelloParam getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

