// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hello.proto
// Protobuf Java Version: 4.29.3

package com.linfp.elephant.grpc;

public interface HelloParamOrBuilder extends
        // @@protoc_insertion_point(interface_extends:hello.HelloParam)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string arg1 = 1;</code>
     *
     * @return The arg1.
     */
    java.lang.String getArg1();

    /**
     * <code>string arg1 = 1;</code>
     *
     * @return The bytes for arg1.
     */
    com.google.protobuf.ByteString
    getArg1Bytes();

    /**
     * <code>int32 arg2 = 2;</code>
     *
     * @return The arg2.
     */
    int getArg2();
}
