// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hello.proto
// Protobuf Java Version: 4.29.3

package com.linfp.elephant.grpc;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.PingRequest)
    com.google.protobuf.MessageOrBuilder {
}
